---
services:
  db:
    image: {{ db_image }}:{{ db_version }}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "{{ db_resources_limits.cpus}}"
          memory: "{{ db_resources_limits.memory }}"
    volumes:
      - {{ db_volume }}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "{{ db_root_password }}"
      MYSQL_DATABASE: "{{ db_database }}"
      MYSQL_USER: "{{ db_user }}"
      MYSQL_PASSWORD: "{{ db_user_password }}"
    logging:
      driver: "{{ db_logging.driver }}"
      options:
        max-size: "{{ db_logging.max_size }}"
        max-file: "{{ db_logging.max_file }}"

  wordpress:
    depends_on:
      - db
    image: {{ wp_image }}:{{ wp_version }}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "{{ wp_resources_limits.cpus }}"
          memory: "{{ wp_resources_limits.memory }}"
    networks:
      - default
      - {{ traefik_docker_network }}
    volumes:
      - {{ wp_volume }}:/var/www/html
      - ./conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_NAME: "{{ db_database}}"
      WORDPRESS_DB_USER: "{{ db_user}}"
      WORDPRESS_DB_PASSWORD: "{{ db_user_password }}"
      WORDPRESS_TABLE_PREFIX: "{{ wp_table_prefix }}"
    logging:
      driver: "{{ wp_logging.driver }}"
      options:
        max-size: "{{ wp_logging.max_size }}"
        max-file: "{{ wp_logging.max_file}}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network={{ traefik_docker_network }}"
      {% if traefik_tls_provider == "letsencrypt" %}
- "traefik.http.routers.{{ wp_router_traefik }}-https.tls=true"
      - "traefik.http.routers.{{ wp_router_traefik }}-https.entrypoints=websecure"
      - "traefik.http.routers.{{ wp_router_traefik }}-https.rule={{ wp_domains }}"
      - "traefik.http.routers.{{ wp_router_traefik }}-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.{{ wp_router_traefik }}-http.rule={{ wp_domains }}"
      - "traefik.http.routers.{{ wp_router_traefik }}-http.entrypoints=web"
      - "traefik.http.routers.{{ wp_router_traefik }}-http.tls.certresolver=letsencrypt"
      {% elif traefik_tls_provider == "cloudflare" %}
- "traefik.http.routers.{{ wp_router_traefik }}-https.tls=true"
      - "traefik.http.routers.{{ wp_router_traefik }}-https.entrypoints=websecure"
      - "traefik.http.routers.{{ wp_router_traefik }}-https.rule={{ wp_domains }}"
      - "traefik.http.routers.{{ wp_router_traefik }}-https.tls.certresolver=cloudflare"
      {% endif %}

networks:
  {{ traefik_docker_network }}:
    external: true